### ISSUE TITLE
Optimisation du mouvement pour suivre un chemin

### ISSUE THREAD

**Issue by agingrasc** [RoboCupULaval/StrategyIA#102]
Dans le nouvel *executor* pour le movement, ajouté les calculs nécessaires pour forcer l'asservissement à produire un mouvement fluide lorsqu'on suit un chemin.

Ceci peut-être obtenu en modifiant la cible de déplacement dynamiquement lorsqu'on arrive proche d'un point du chemin et qu'un autre point reste à atteindre. L'asservissement n'a aucune notion de "chemin" et ne devrait pas non plus en acquérir.

**Comment by MaximeGLegault** [comment]
Est-ce que cela pourrais avoir des répercussions sur les pathfinders ou le module s'occupant du pathfinder?
Dans le cas où on voudrait produire un mouvement allongé en arc de cercle est ce qu'il faudrait s'assurer que le pathfinding ne nous retourne pas un suite de point trop collée ou qu'il s'assure de trouvé des chemins larges pour assurer l'allongement du parcous du robot. Chose à vérifier.
