### ISSUE TITLE
Deal with TODO/FIXME spread out in code

### ISSUE THREAD

**Issue by david2194** [RoboCupULaval/StrategyIA#204]

**Comment by sim0504** [comment]
This issue will never be closed...

**Comment by PhiBabin** [comment]
We could add a on-going tag?

**Comment by frstp64** [comment]
I will remove the TODOs and FIXMEs from dev, and transfer+group them to github issues. There is about 80 of them in total. I expect approximately 30 valid github issues. This will break this issue into manageable chunks.

**Comment by frstp64** [comment]
#327 would probably allow to close this issue. Feel free to close it if it gets merged.
