### ISSUE TITLE
Unit test the code

### ISSUE THREAD

**Issue by david2194** [RoboCupULaval/StrategyIA#206]

**Comment by wonwon0** [comment]
Babin, t'as fix des units tests, maybe cest legit de close l'issue

**Comment by PhiBabin** [comment]
J'ai fixé les tests existants, mais la majorité de ce que l'on a rajouté n'est pas couvert. Je préfère attendre que les stratégies et tactics soient testable avant de close. On peut aussi utilisé cette issue comme une on-going issue qui est toujours là?

**Comment by sim0504** [comment]
Je suggère de faire des issues plus spécifique. Cest extrêmement broad.

**Comment by sim0504** [comment]
Des issues plus spécifiques ont été créées
