### ISSUE TITLE
Remove unused strategy/tactics in StrategyBook/TacticsBook

### ISSUE THREAD

**Issue by david2194** [RoboCupULaval/StrategyIA#208]

**Comment by PhiBabin** [comment]
Je propose d'avoir un Unit test qui passe à travers le Strategy/TacticsBook et qui fail si l'une des strategy/tactics n'a pas de test unitaire. Comme cela on va pu avoir le problème où tu peux faire planter l'IA en choisissant la mauvaise stratégie dans UI-debug.

**Comment by david2194** [comment]
Faudrait en discuter, mais pour le moment je ne crois pas que notre architecture permets de tester facilement les Strategy/Tactics. Cet aspect là risque, à terme, de dépendre sur #207
