### ISSUE TITLE
Prevent access to tactics not in tacticBook

### ISSUE THREAD

**Issue by david2194** [RoboCupULaval/StrategyIA#212]

**Comment by PhiBabin** [comment]
On pourrait faire comme UI debug fait pour la reception de packet: toutes les tactics qui sont le dossier tactics/ sont automatiquement rajouté au tacticBook. Ainsi, cela évite que l'on laisse des tactics que nous utilisons pas.

**Comment by david2194** [comment]
Le problème que je voyais c'était plutôt l'inverse. Nos strategy passent pas par le tacticBook pour importer leur tactics, elles vont direct faire des `from ../Tactic/GoalKeeper import GoalKeeper`. Ca fait des imports partout, et si un jour ot strategy peuvent utilement hériter d'autres strategies, on va se ramasser à importer mer et monde à chaque fois

**Comment by PhiBabin** [comment]
Tu vois un genre service locator pour tactic, qui utiliserait le tacticBook pour évité d'avoir un shit load d'import?

**Comment by david2194** [comment]
Quelque chose du genre, oui. J'ai pas encore trop élaboré les détails plus techniques, mais au moins ca laisserais la gestion de l'import/localisation des tactics au TacticBook, et les Strategy pourraient se focuser sur ce qu'elles sont réellement sensées faire

**Comment by PhiBabin** [comment]
Je vais close, puisque cela ne semble pas être un problème urgent. Reopen quand qu'un sera intéressé
