### ISSUE TITLE
Refactor IACommand

### ISSUE THREAD

**Issue by PhiBabin** [RoboCupULaval/StrategyIA#215]
IACommand currently is just a big dictionnary. Each time we add a new command, we need to add new field to it. So the contructor become a monster and it breaks all the time.
The solution is either to pass a list of command instead of one big object or to have a Builder contruct a IACommand.

**Comment by MaximeGLegault** [comment]
Branche refonte_communication: J'ai changé l'AICommand pour le namedtuple de Simon, déplacer l'ancien dans le fichier Util/ai_command_shit en attendant de faire les changement partout ailleurs que idle et go to position path.

Une factorie pour IACommand serait bien.

**Comment by PhiBabin** [comment]
Je vais changé les actions par un builder de ai_command.

**Comment by PhiBabin** [comment]
See #248
