### ISSUE TITLE
ball object inconsitant avec les autres objets de game_state (players)

### ISSUE THREAD

**Issue by wonwon0** [RoboCupULaval/StrategyIA#223]
pour get la vitesse cartesienne de la balle il faut appeler: "ball.velocity" qui retourne un objet POSITION.

si on fait la même chose avec player: "ourplayer.velocity" qui retoure une objet SPEEDPOSE qui est ni plsu ni moins qu'un objet POSE contenant un objet POSITION et une orientation.

Il faudrait modifier l'objet ball pour qu'il soit consistant avec l'objet Ourplayer.

**Comment by PhiBabin** [comment]
Je crois que c'est comme cela parce que robot a une vitesse angular, pas la balle. Mais c'est vrai que c'est pas consistant.

**Comment by sim0504** [comment]
fix in last PR.
