### ISSUE TITLE
Kalman sometime overestimate the robot's rotation speed

### ISSUE THREAD

**Issue by PhiBabin** [RoboCupULaval/StrategyIA#226]
When the rotation speed is overestimate for a few secondes, the speed read `inf` and the robot's position becomes `nan`. The bug is visible in the ui-debug when the Kalman estimation spins really fast.
To temporary handle this issue, the speed is reset to zero when the speed is too large. 
I don't know if the new architecture's Kalman suffers from the same problem.

**Comment by sim0504** [comment]
The new tracker dont seems to have this problem.
