### ISSUE TITLE
Kill switch, for all process

### ISSUE THREAD

**Issue by PhiBabin** [RoboCupULaval/StrategyIA#228]
La nouvelle architecture (un peu comme l'ancienne) a comme défaut que si l'un des processus/threads crash, le reste du système continue d'être exécuté.
Il faudrait donc que chaque process soit exécuté dans un try catch et que en cas de crash un signal est enclenché. Ensuite dans chaque main loop de chaque processus, il y a une vérification d'un signal global (ex: `while engine.ok()`)

**Comment by frstp64** [comment]
Problem probably solved,
see https://github.com/RoboCupULaval/StrategyIA/pull/234

What is detected:
- One of the four subprocesses of the engine crashes
- The Engine crashes
- The Coach crashes
