### ISSUE TITLE
Ai crash quand ball est a (0,0) et qu'on call gokick avec grsim

### ISSUE THREAD

**Issue by wonwon0** [RoboCupULaval/StrategyIA#245]
Ai crash quand ball est a (0,0) et qu'on call gokick avec grsim

je sais pas si le bug est consistant, mais quand la balle est a (0,0), le ball service delete plein de ball.

**Comment by wonwon0** [comment]
Simon, je t'ai assign sur celle là just in case que tu as une idée pk c'Est de même, notify me si t'as pas le temps de check ca, je vais le faire si non.

**Comment by sim0504** [comment]
peux tu preciser une branche please

**Comment by wonwon0** [comment]
refonte_communication

**Comment by sim0504** [comment]
Peux tu me donner le log dans la console

**Comment by sim0504** [comment]
Je dois dire que le multiball service est broken depuis le merge dans l'ai. Faudrai que je le fix.

**Comment by PhiBabin** [comment]
Présentement, il y a rien qui crash lorsque l'on fait les actions mientionné plus haut. Par contre, le robot ne peut pas kicker la balle parce qu'il y a des robots invisibles au centre du terrain qui sont considéré collisionable.

**Comment by barch2712** [comment]
Je me met la dessus

**Comment by sim0504** [comment]
afaik this is fix.
