### ISSUE TITLE
Fix MultiBallService

### ISSUE THREAD

**Issue by sim0504** [RoboCupULaval/StrategyIA#247]
At the moment, the multi ball service support only one ball.

**Comment by PhiBabin** [comment]
Rename it `SingleBallService`. Done.

**Comment by sim0504** [comment]
I mean, it need to remove the ball obervation that do not match the correct ball. It's kind of broken at the moment. I still expect the service to return 1 ball. The name might be wrong.

**Comment by sim0504** [comment]
It's now remove. Solved.
