### ISSUE TITLE
Command sender should be executed in the same loop has the engine

### ISSUE THREAD

**Issue by PhiBabin** [RoboCupULaval/StrategyIA#253]
Currently, the command sender to grsim and to the communication tower are in a differente process and its queue is feed by the engine main loop. We want to reduce the delay between generating a speed command and publishing it, so it makes sense that they are in the same loop. Also, since the engine has a fix frame rate, we can ajust the frequency to the maximum frequency of the subscriber (60fps for grsim and 100fps for communication tower).

**Comment by sim0504** [comment]
see https://github.com/RoboCupULaval/StrategyIA/tree/fix/remove_cmd_sender_process
