### ISSUE TITLE
Clean pathfinder code

### ISSUE THREAD

**Issue by sim0504** [RoboCupULaval/StrategyIA#269]
The code for handling the pathfinder is a bit harsh to look at. It can be improve by cleaning the code and use function to compute some of the big if condition.

**Comment by PhiBabin** [comment]
Should be refactor with TDD.

**Comment by wonwon0** [comment]
Yer clean kon code ok?!?!

**Comment by sim0504** [comment]
Tu as transcandé à un niveau supérieur !

**Comment by wonwon0** [comment]
Ok ok jvais mettre des comments

**Comment by sim0504** [comment]
Done. Need to added Tests
