### ISSUE TITLE
Ball tracker crash when no ball on field

### ISSUE THREAD

**Issue by sim0504** [RoboCupULaval/StrategyIA#274]

**Comment by PhiBabin** [comment]
What could we do when there is no ball on the field?

**Comment by sim0504** [comment]
I think we just need to detect in the tracker that there is no ball output by the ball tracker and remove the ball field in the game_state dict.

**Comment by PhiBabin** [comment]
What happend to a GoKick when there is no ball on the field? Either we just use the last seen position of the ball or we have something that stop tactic that require a ball.

**Comment by sim0504** [comment]
we should wait for geometry and a ball in the ai process
