### ISSUE TITLE
Bad management of invalid player ids in _parse_tactic

### ISSUE THREAD

**Issue by frstp64** [RoboCupULaval/StrategyIA#287]
> ./ai/executors/debug_executor.py:82:        # FIXME this pid thingy is getting out of control

The problem: Having to try to get the player id and return if there isn't one in the command is not clean. The player id should always be valid, or else the command should not be sent to _parse_tactic in the first place.

If there are commands without IDs, they should be explicitly taken care of.

**Comment by sim0504** [comment]
This is not in the file debug_executor
