### ISSUE TITLE
Clean geometry.py's remove_duplicates function

### ISSUE THREAD

**Issue by frstp64** [RoboCupULaval/StrategyIA#297]
> ./Util/geometry.py:54:    # TODO: Clean that. Seems to complicate for nothing. + Varible return argument

The problem: The current version of remove_duplicates is complicated and has multiple return points. It should be simplified to contain a single return point.

Another enhancement is the removal of function handles that are used once, like seen_add and seen2_add. They clutter the code.

**Comment by sim0504** [comment]
I think they are not use anymore. Will check that tommorow.

**Comment by sim0504** [comment]
remove in #332
