### ISSUE TITLE
Replace the Path class' start and end parameters with a list of points

### ISSUE THREAD

**Issue by frstp64** [RoboCupULaval/StrategyIA#298]
> ./Util/path.py:7:    # TODO: Instead of start and end, should it be more logical to have the list of points?

The problem: the Path object receives a start and end position. It would be more logical to receive a list of points, thus enabling more complex paths to be created later.

**Comment by sim0504** [comment]
Actually at the moment this make more sense. the classmethod from_points allow this feature.
