### ISSUE TITLE
Enhance the Pathfinder class

### ISSUE THREAD

**Issue by frstp64** [RoboCupULaval/StrategyIA#306]
> ./ai/Algorithm/IntelligentModule.py:44:    # TODO Make this class better please!
> ./ai/Algorithm/IntelligentModule.py:48:        # TODO see if we can remove this part!
> ./ai/Algorithm/IntelligentModule.py:50:        # TODO insert constant for max numbers of robots below instead of 11!

The problem: The class does nothing outside of a print function. The following problems should be solved:

- [ ] Remove the 11 magic number and replace it with the appropriate constant from the appropriate configuration file.
- [ ] Modify the printing function to return a prettified version of the paths.
- [ ] Simplify the initialization logic.

**Comment by sim0504** [comment]
all done in fix/pathfinder 1 :)
