### ISSUE TITLE
Move the constant 0.05 from Coach to the configuration file

### ISSUE THREAD

**Issue by frstp64** [RoboCupULaval/StrategyIA#307]
> ./ai/coach.py:71:                sleep(0.05)  # TODO: Put it in config file

The problem: The current sleep time is hard-coded into the Coach object, it should be configured in the configuration file.

Additionally, the logic should be changed to allow sleep_until-like functionality, for more regular calls time-wise. This can be done by adding a time attribute that is incremented and used to compute the immediate sleep time until the next time.

**Comment by sim0504** [comment]
The delay could also be increased

**Comment by sim0504** [comment]
#337
