### ISSUE TITLE
Test and repair stay_inside_goal_area and stay_outside_goal_area in Shitty_Field.py

### ISSUE THREAD

**Issue by frstp64** [RoboCupULaval/StrategyIA#310]
> ./ai/GameDomainObjects/Shitty_Field.py:89:        # TODO Not tested: stayInsideGoalArea
> ./ai/GameDomainObjects/Shitty_Field.py:118:        # TODO Not tested: stayOutsideGoalArea

The problem: The current methods for staying inside and outisde the goal area are not tested, they need to be tested and repaired until they are working.

**Comment by PhiBabin** [comment]
Shitty_field is getting delete
