### ISSUE TITLE
Set KICKSPEED in the constants for both sides in Shitty_Field.py

### ISSUE THREAD

**Issue by frstp64** [RoboCupULaval/StrategyIA#311]
> ./ai/GameDomainObjects/Shitty_Field.py:257:    # TODO KICKSPEED
> ./ai/GameDomainObjects/Shitty_Field.py:339:    # TODO KICKSPEED

The problem: The kick speed parameter is not set in Shitty_Field.py, it should be set there. It may be fixed somewhere else in the code and needs to be replaced to use this one.

**Comment by PhiBabin** [comment]
Shitty_Field is getting delete soon
