### ISSUE TITLE
Change UI to send better packets back with the arguments (args) in it.

### ISSUE THREAD

**Issue by frstp64** [RoboCupULaval/StrategyIA#313]
> ./ai/executors/play_executor.py:89:        # TODO ui must send better packets back with the args.

The problem: The current UI packets contain no args?

**Comment by PhiBabin** [comment]
It's more that the ui is sending one args and some tactic use is other does not. So this comment is related to https://github.com/RoboCupULaval/UI-Debug/issues/89
