### ISSUE TITLE
Complete or remove the kickcharge action

### ISSUE THREAD

**Issue by frstp64** [RoboCupULaval/StrategyIA#316]
> ./ai/STA/Action/kick_charge.py:21:        # todo charge kick here please/ask Simon what kicktype is supposed to be

The problem: The KickCharge Action does nothing. It should either be removed (if the robot keeps its kick charged) or completed.

**Comment by frstp64** [comment]
Also, please investigate this location, it has some need for charging?

> ./ai/STA/Tactic/pass_to_player.py:39:        # todo charge kick here please/ask Simon what kicktype is supposed to be

**Comment by sim0504** [comment]
Action are replace with CmdBuilder. This will be fix in the PR of Simon lemay
