### ISSUE TITLE
Investigate if use_pathfinder is still needed in RotateAround's exec method.

### ISSUE THREAD

**Issue by frstp64** [RoboCupULaval/StrategyIA#317]
> ./ai/STA/Action/rotate_around.py:96:        # TODO The old code used "use_pathfinder"

The problem: use_pathfinder was used before. It was probably not needed. This needs to be checked.

**Comment by PhiBabin** [comment]
I think RotateAround is getting deleted?

**Comment by sim0504** [comment]
yes
