### ISSUE TITLE
Complete the HumanControl assign_tactic method

### ISSUE THREAD

**Issue by frstp64** [RoboCupULaval/StrategyIA#318]
> ./ai/STA/Strategy/human_control.py:26:            self.game_state.map_players_to_roles_by_player_id({robot_id: Role.FIRST_ATTACK})  # TODO

The problem: The current version of the code assigns the attack role to the human, this may not be desired all the time.

**Comment by PhiBabin** [comment]
Fixed in feature/default_tactic
