### ISSUE TITLE
Check and repair the Strategy comparison functions

### ISSUE THREAD

**Issue by frstp64** [RoboCupULaval/StrategyIA#322]
> ./ai/STA/Strategy/strategy.py:110:    # TODO check if this is correct MGL 2017/06/16

The problem: the current Strategy class has comparison operators that check if two strategies are the same by checking their string representation. This string representation uses the class's name to do this. This should be replaced with a cleaner version, and may not even be needed.

**Comment by PhiBabin** [comment]
This is not really a problem the only place in the code were a comparaison is done (in play_executor), the string representation make sense.
