### ISSUE TITLE
Add argument configuration for frequently change parameters

### ISSUE THREAD

**Issue by PhiBabin** [RoboCupULaval/StrategyIA#331]
There are some constant that get change frequently and computer specific. For example, the frame rate of the engine depends of the speed of the user's computer and thus must not be commit/push. It would preferable if we pass has argument these parameters, so they are not commited.
I suggest having these parameters as arguments:
 - our team color : second mandatory argument after the path to the configuration file
 - engine's frame rate : `--engine_fps`
 - unlock engine's frame rate : `--unlock_engine_fps`
 - are we on the positive or negative side of the field : `--on_negative_side`

**Comment by sim0504** [comment]
#337
