### ISSUE TITLE
Remove singleton for object which can be injected

### ISSUE THREAD

**Issue by PhiBabin** [RoboCupULaval/StrategyIA#332]
The following class are singleton even if they are either use at 2-3 places or content only static method:
 - `PlayState`: use in autoplay and by PlayExecutor
 - `DebugExecutor`: only used by the Coach
 - `UIDebugCommandFactory`: only contains static method (maybe change it to a module?)
- `PlayExecutor`: only use by Autoplay and Coach

Having singleton everywhere is not a good design choice, especially when there is no reason for it.

**Comment by sim0504** [comment]
#334
