### ISSUE TITLE
API InfoManager

### ISSUE THREAD

**Issue by agingrasc** [RoboCupULaval/StrategyIA#48]
(modification ultérieur à la demande possible)
- <strike>Set player_skill_target_goal, à séparer en 3</strike>
- Refléter refactor STA (skill -> action, play -> strategy)
- Utiliser des objet/namedtuple pertinent pour représenter le gamestate.
  Actuellement des dictionnaires, qui utilise des strings comme clef quand un int ferait l'affaire, sont utilisés, leur manipulation directe est moins aisé quand l'API de l'info_manager ne suffit pas

**Comment by AlexandraMercier** [comment]
Refonte du InfoManager:
- Séparer l'état du jeu de InfoManager: Ce sera un singleton avec un update et des "get" read-only.
- La gestion des modules intelligents se fera par une classe singleton, qui chargera les modules dans __init__ avec un fichier config.
- La refonte va causer des bris dans l'API, réparer les bris

**Comment by AlexandraMercier** [comment]
Je suis prête à commencer l'intégration du Game State manager et du Module manager dans l'API. Toutefois, il me manque des modifications en pull request qui enlèvent des dépendances au info manager.
