### ISSUE TITLE
Améliorer les passes

### ISSUE THREAD

**Issue by PhiBabin** [RoboCupULaval/StrategyIA#517]
Présentement la logique de passe est très simple. Existe encore des cas ou la passe est évité par le receiveur.

**Comment by PhiBabin** [comment]
Une première étape serait de cleaner la fonction `trajectory_score`, elle est horrible. Cette fonction évalue le score de faire une passe à un robot alliée.

**Comment by SimLemay** [comment]
#554 La solution commence à prendre forme.
