### ISSUE TITLE
Fix waypoints movements

### ISSUE THREAD

**Issue by barch2712** [RoboCupULaval/StrategyIA#524]
When using waypoints to go from point A to B and then C, if there is an obstacle between A and B, the robot will directly go towards point C until it has a straight line clearance between its position and point B. This makes the trajectory a lot rounder between A and B and thus taking more time to complete. Also, there is sometimes a flickering between B and C as the current destination, also slowing down the robot.

**Comment by wonwon0** [comment]
fixed dans #541
