### ISSUE TITLE
Goal aware Goalkeeper

### ISSUE THREAD

**Issue by PhiBabin** [RoboCupULaval/StrategyIA#525]
Le goalkeeper peut être pris en arrière du but, il n'est pas capable de revenir sur le jeu, parce que le pathfinder ne sait pas que le goal est collision able. Il faudrait rajouté un check dans le code du goal keeper qui détecte lorsqu'il  est en dehors du but et qui fait une trajectoire pour qu'il revient sur le jeu.

**Comment by SimLemay** [comment]
#537
