### ISSUE TITLE
Ajouter des options lignes de commandes

### ISSUE THREAD

**Issue by agingrasc** [RoboCupULaval/StrategyIA#60]
Le lancement de l'IA devrait permettre de passer des paramètres diverses:
- --test_bench : lance un test_bench pour la simulation/vrai vie
- --no_debug : coupe les fonctionnalités de debug

Le point est d'avoir le code en place (pas très lourd puisque dans la stdlib) et de pouvoir par la suite ajouter rapidement et facilement d'autres options qui seraient utile.

**Comment by MaximeGLegault** [comment]
Options de ligne de commande ajoutées sauf celles mentionnées plus haut.

**Comment by MaximeGLegault** [comment]
Fichier de configuration remplace les lignes de commandes. Juste à mettre comme option au scipt main.py un des fichiers cfg qui se trouve dans le dossier config -> python main.py config/sim_kalman_redirect.cfg
